In [5]:
import tensorflow as tf

# 强制 TensorFlow 仅使用 CPU
tf.config.set_visible_devices([], 'GPU')  # 隐藏所有 GPU

# 检查当前可见设备
visible_devices = tf.config.get_visible_devices()
print("Visible devices:", visible_devices)

# 创建张量并进行运算
tensor_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# 加法
tensor_add = tensor_a + tensor_b  # 等价于 tf.add(tensor_a, tensor_b)

# 减法
tensor_sub = tensor_a - tensor_b  # 等价于 tf.subtract(tensor_a, tensor_b)

# 乘法（逐元素相乘）
tensor_mul = tensor_a * tensor_b  # 等价于 tf.multiply(tensor_a, tensor_b)

# 除法（逐元素相除）
tensor_div = tensor_a / tensor_b  # 等价于 tf.divide(tensor_a, tensor_b)

# 打印结果
print("Tensor A:")
print(tensor_a.numpy())  # 转换为 NumPy 数组以便打印

print("\nTensor B:")
print(tensor_b.numpy())

print("\nAddition (A + B):")
print(tensor_add.numpy())

print("\nSubtraction (A - B):")
print(tensor_sub.numpy())

print("\nMultiplication (A * B):")
print(tensor_mul.numpy())

print("\nDivision (A / B):")
print(tensor_div.numpy())

Visible devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
Tensor A:
[[1. 2.]
 [3. 4.]]

Tensor B:
[[5. 6.]
 [7. 8.]]

Addition (A + B):
[[ 6.  8.]
 [10. 12.]]

Subtraction (A - B):
[[-4. -4.]
 [-4. -4.]]

Multiplication (A * B):
[[ 5. 12.]
 [21. 32.]]

Division (A / B):
[[0.2        0.33333334]
 [0.42857143 0.5       ]]
